// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnm2WvmZFAQyRnYnMLgUDXJnWqaHMeNGo',
    appId: '1:811021311640:web:da80ce006b1200f6ecbaed',
    messagingSenderId: '811021311640',
    projectId: 'food-delivery-app-387918',
    authDomain: 'food-delivery-app-387918.firebaseapp.com',
    storageBucket: 'food-delivery-app-387918.appspot.com',
    measurementId: 'G-LJ3LEX585R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbGiLHN0-9NlBfCZWxN8YCldULsKoVIGw',
    appId: '1:811021311640:android:73036b380c3d8ef1ecbaed',
    messagingSenderId: '811021311640',
    projectId: 'food-delivery-app-387918',
    storageBucket: 'food-delivery-app-387918.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1YB36-_24DUlZ_Y-b2xx40XYR9qTd1Ns',
    appId: '1:811021311640:ios:3e90f84823305cbcecbaed',
    messagingSenderId: '811021311640',
    projectId: 'food-delivery-app-387918',
    storageBucket: 'food-delivery-app-387918.appspot.com',
    iosClientId: '811021311640-l8fkdd0k9tq1808233crd5qohskf8nm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1YB36-_24DUlZ_Y-b2xx40XYR9qTd1Ns',
    appId: '1:811021311640:ios:3e90f84823305cbcecbaed',
    messagingSenderId: '811021311640',
    projectId: 'food-delivery-app-387918',
    storageBucket: 'food-delivery-app-387918.appspot.com',
    iosClientId: '811021311640-l8fkdd0k9tq1808233crd5qohskf8nm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryBackend',
  );
}
